name: Pylint

on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./live_pipeline/requirements.txt
        pip install -r ./dashboard/requirements.txt
        pip install -r ./archive_pipeline/requirements.txt
    - name: Analysing push files with pylint
      run: |
        pylint --fail-under=8 $(git ls-files '*.py')
